name: Update Latest URL

on:
  schedule:
    - cron: "0 23 * * *"   # ‚è∞ jalan tiap 1 jam sekali
  workflow_dispatch:      # bisa juga manual run dari GitHub

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python req_link.py

      - name: Commit & Push latest_url.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add latest_url.txt
          git commit -m "Update latest_url.txt" || echo "No changes to commit"
          git pull --rebase
          git push
